[profile.release]
panic = 'unwind'

[workspace]
members = ['node', 'pallets/*', 'runtime']
resolver = "2"

[workspace.dependencies]
clap = "4.5.27"
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.6.12' }
flexi_logger = "0.22.5"
futures = "0.3.31"
hex-literal = "0.3.1"
jsonrpsee = { version = "0.24.8", features = ["server"] }
log = "0.4.25"
parking_lot = "0.12.3"
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false }

frame-benchmarking = { default-features = false, version = "39.0.0" }
frame-benchmarking-cli = { default-features = false, version = "46.1.0" }
frame-executive = { default-features = false, version = "39.1.0" }
frame-support = { default-features = false, version = "39.1.0" }
frame-system = { default-features = false, version = "39.1.0" }
frame-system-benchmarking = { default-features = false, version = "39.0.0" }
frame-system-rpc-runtime-api = { default-features = false, version = "35.0.0" }
pallet-aura = { default-features = false, version = "38.1.0" }
pallet-balances = { default-features = false, version = "40.1.0" }
pallet-grandpa = { default-features = false, version = "39.1.0" }
pallet-insecure-randomness-collective-flip = { default-features = false, version = "27.0.0" }
pallet-sudo = { default-features = false, version = "39.0.0" }
pallet-timestamp = { default-features = false, version = "38.0.0" }
pallet-transaction-payment = { default-features = false, version = "39.1.0" }
pallet-transaction-payment-rpc = { default-features = false, version = "42.0.0" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = "39.0.0" }
sc-basic-authorship = { default-features = false, version = "0.48.0" }
sc-cli = { default-features = false, version = "0.50.1" }
sc-client-api = { default-features = false, version = "38.0.0" }
sc-consensus = { default-features = false, version = "0.47.0" }
sc-consensus-aura = { default-features = false, version = "0.48.0" }
sc-consensus-manual-seal = { default-features = false, version = "0.49.0" }
sc-consensus-grandpa = { default-features = false, version = "0.33.0" }
sc-executor = { default-features = false, version = "0.41.0" }
sc-keystore = { default-features = false, version = "34.0.0" }
sc-network = { default-features = false, version = "0.48.3" }
sc-offchain = { default-features = false, version = "43.0.0" }
sc-rpc = { default-features = false, version = "43.0.0" }
sc-rpc-api = { default-features = false, version = "0.47.0" }
sc-service = { default-features = false, version = "0.49.0" }
sc-telemetry = { default-features = false, version = "28.0.0" }
sc-transaction-pool = { default-features = false, version = "38.1.0" }
sc-transaction-pool-api = { default-features = false, version = "38.1.0" }
scale-info = { version = "2.11.5", default-features = false, features = ["derive"] }
sp-api = { default-features = false, version = "35.0.0" }
sp-block-builder = { default-features = false, version = "35.0.0" }
sp-blockchain = { default-features = false, version = "38.0.0" }
sp-consensus = { default-features = false, version = "0.41.0" }
sp-consensus-aura = { default-features = false, version = "0.41.0" }
sp-consensus-grandpa = { default-features = false, version = "22.0.0" }
sp-core = { default-features = false, version = "35.0.0" }
sp-io = { default-features = false, version = "39.0.1" }
sp-inherents = { default-features = false, version = "35.0.0" }
sp-offchain = { default-features = false, version = "35.0.0" }
sp-runtime = { default-features = false, version = "40.1.0" }
sp-session = { default-features = false, version = "37.0.0" }
sp-staking = { default-features = false, version = "37.0.0" }
sp-std = { default-features = false, version = "14.0.0" }
sp-timestamp = { default-features = false, version = "35.0.0" }
sp-transaction-pool = { default-features = false, version = "35.0.0" }
sp-version = { default-features = false, version = "38.0.0" }
substrate-frame-rpc-system = { default-features = false, version = "42.0.0" }
substrate-wasm-builder =  { default-features = false, version = "25.0.1" }

node-template-runtime = { path = 'runtime', version = '3.0.0' }
pallet-template-transaction-payment = { path = 'pallets/template-transaction-payment', default-features = false, version = '3.0.0' }
up-sponsorship = { path = 'primitives/sponsorship', default-features = false, version = '0.1.0' }
