[profile.release]
panic = 'unwind'

[workspace]
members = ['node', 'pallets/*', 'runtime']
resolver = "2"

[workspace.dependencies]
clap = "4.5.3"
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.1.2' }
flexi_logger = "0.22.5"
futures = "0.3.17"
hex-literal = "0.3.1"
jsonrpsee = { version = "0.24.3", features = ["server"] }
log = "0.4.14"
parking_lot = "0.12.1"
serde = { version = "1.0.130", default-features = false }
serde_json = { version = "1.0.128", default-features = false }

frame-benchmarking = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
frame-benchmarking-cli = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
frame-executive = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
frame-support = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
frame-system = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
frame-system-benchmarking = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
frame-system-rpc-runtime-api = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
pallet-aura = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
pallet-balances = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
pallet-grandpa = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
pallet-insecure-randomness-collective-flip = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
pallet-sudo = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
pallet-timestamp = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
pallet-transaction-payment = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
pallet-transaction-payment-rpc = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-basic-authorship = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-cli = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-client-api = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-consensus = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-consensus-aura = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-consensus-grandpa = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-executor = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-keystore = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-network = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-offchain = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-rpc = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-rpc-api = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-service = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-telemetry = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-transaction-pool = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sc-transaction-pool-api = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
scale-info = { default-features = false, version = "2.11.3", features = ['derive']}
sp-api = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-block-builder = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-blockchain = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-consensus = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-consensus-aura = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-consensus-grandpa = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-core = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-io = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-inherents = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-offchain = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-runtime = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-session = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-staking = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-std = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-timestamp = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-transaction-pool = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
sp-version = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
substrate-frame-rpc-system = { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }
substrate-wasm-builder =  { default-features = false, git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }

node-template-runtime = { path = 'runtime', version = '3.0.0' }
pallet-template-transaction-payment = { path = 'pallets/template-transaction-payment', default-features = false, version = '3.0.0' }
up-sponsorship = { path = 'primitives/sponsorship', default-features = false, version = '0.1.0' }