[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
build = 'build.rs'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2021'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'node-template'
publish = false
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bin]]
name = 'node-template'

[build-dependencies.substrate-build-script-utils]
version = '3.0.0'

[dependencies]
futures = '0.3.17'
log = '0.4.14'
flexi_logger = "0.22.5"
parking_lot = '0.12.1'
clap = "4.0.9"
jsonrpsee = { version = "0.15.1", features = ["server"] }

[dependencies.node-template-runtime]
path = '../runtime'
version = '3.0.0'

[dependencies.frame-benchmarking]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.frame-benchmarking-cli]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.pallet-transaction-payment-rpc]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-basic-authorship]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-cli]
features = ['wasmtime']
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-client-api]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-consensus]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-consensus-aura]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-executor]
features = ['wasmtime']
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-finality-grandpa]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-keystore]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-rpc]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-rpc-api]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-service]
features = ['wasmtime']
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-telemetry]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-transaction-pool]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sc-transaction-pool-api]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sp-api]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sp-block-builder]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sp-blockchain]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sp-consensus]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sp-consensus-aura]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sp-core]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sp-finality-grandpa]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sp-runtime]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.sp-timestamp]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[dependencies.substrate-frame-rpc-system]
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.33-asset-destroy"

[features]
default = []
runtime-benchmarks = ['node-template-runtime/runtime-benchmarks']
