[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
build = 'build.rs'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2021'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'node-template'
publish = false
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[package.metadata.deppatcher.originals.build-dependencies]
substrate-build-script-utils = { version = "9.0.0" }

[[bin]]
name = 'node-template'

[build-dependencies]
substrate-build-script-utils = "11.0.0"

[dependencies]
clap = "4.4.6"
flexi_logger = "0.27.2"
frame-benchmarking = "34.0.0"
frame-benchmarking-cli = "38.0.0"
futures = "0.3.28"
jsonrpsee = { version = "0.22.5", features = ["server"] }
log = "0.4.20"
node-template-runtime = { path = "../runtime" }
pallet-transaction-payment-rpc = "36.0.0"
parking_lot = "0.12.1"
sc-basic-authorship = "0.40.0"
sc-cli = "0.42.0"
sc-client-api = "34.0.0"
sc-consensus = "0.39.1"
sc-consensus-aura = "0.40.0"
sc-consensus-grandpa = "0.25.0"
sc-executor = "0.38.0"
sc-keystore = "31.0.0"
sc-network = "0.40.0"
sc-rpc = "35.0.0"
sc-rpc-api = "0.39.0"
sc-service = "0.41.0"
sc-telemetry = "20.0.0"
sc-transaction-pool = "34.0.0"
sc-transaction-pool-api = "34.0.0"
serde_json = "1.0.115"
sp-api = "32.0.0"
sp-block-builder = "32.0.0"
sp-blockchain = "34.0.0"
sp-consensus = "0.38.0"
sp-consensus-aura = "0.38.0"
sp-consensus-grandpa = "19.0.0"
sp-core = "33.0.1"
sp-runtime = "37.0.0"
sp-timestamp = "32.0.0"
substrate-frame-rpc-system = "34.0.0"

[features]
default = []
runtime-benchmarks = ['node-template-runtime/runtime-benchmarks']
