[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
build = 'build.rs'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2021'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'node-template'
publish = false
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[package.metadata.deppatcher.originals.dependencies]
frame-benchmarking = { version = "25.0.0" }
frame-benchmarking-cli = { version = "29.0.0" }
pallet-transaction-payment-rpc = { version = "27.0.0" }
sc-basic-authorship = { version = "0.31.0" }
sc-cli = { version = "0.33.0" }
sc-client-api = { version = "25.0.0" }
sc-consensus = { version = "0.30.0" }
sc-consensus-aura = { version = "0.31.0" }
sc-consensus-grandpa = { version = "0.16.0" }
sc-executor = { version = "0.29.0" }
sc-keystore = { version = "22.0.0" }
sc-network = { version = "0.31.0" }
sc-rpc = { version = "26.0.0" }
sc-rpc-api = { version = "0.30.0" }
sc-service = { version = "0.32.0" }
sc-telemetry = { version = "12.0.0" }
sc-transaction-pool = { version = "25.0.0" }
sc-transaction-pool-api = { version = "25.0.0" }
sp-api = { version = "23.0.0" }
sp-block-builder = { version = "23.0.0" }
sp-blockchain = { version = "25.0.0" }
sp-consensus = { version = "0.29.0" }
sp-consensus-aura = { version = "0.29.0" }
sp-consensus-grandpa = { version = "10.0.0" }
sp-core = { version = "25.0.0" }
sp-runtime = { version = "28.0.0" }
sp-timestamp = { version = "23.0.0" }
substrate-frame-rpc-system = { version = "25.0.0" }

[package.metadata.deppatcher.originals.build-dependencies]
substrate-build-script-utils = { version = "9.0.0" }

[[bin]]
name = 'node-template'

[build-dependencies]
substrate-build-script-utils = { git="https://github.com/paritytech/polkadot-sdk", rev="1e5f5fe9086233a464ee249de74e4df959b8eb15" }

[dependencies]
clap = { workspace = true }
flexi_logger = { workspace = true }
futures = { workspace = true }
jsonrpsee = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
serde_json = { workspace = true }

node-template-runtime = { workspace = true }
frame-benchmarking = { workspace = true }
frame-benchmarking-cli = { workspace = true }
pallet-transaction-payment-rpc = { workspace = true }
sc-basic-authorship = { workspace = true }
sc-cli = { workspace = true }
sc-client-api = { workspace = true }
sc-consensus = { workspace = true }
sc-consensus-aura = { workspace = true }
sc-executor = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sc-keystore = { workspace = true }
sc-network = { workspace = true }
sc-offchain = { workspace = true }
sc-rpc = { workspace = true }
sc-rpc-api = { workspace = true }
sc-service = { workspace = true }
sc-telemetry = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-timestamp = { workspace = true }
substrate-frame-rpc-system = { workspace = true }


[features]
default = []
runtime-benchmarks = ['node-template-runtime/runtime-benchmarks']
